// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRdoEd3p-qAjCH1zegOn8V8C0ibdio1wo',
    appId: '1:1014403393538:web:821799fdd4bae8845c9f1b',
    messagingSenderId: '1014403393538',
    projectId: 'pomodoro-knight-ed680',
    authDomain: 'pomodoro-knight-ed680.firebaseapp.com',
    storageBucket: 'pomodoro-knight-ed680.firebasestorage.app',
    measurementId: 'G-2CFZXE9TTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv7LL2wq6MsIkcL_JqzmDBbU2T5zQpIx8',
    appId: '1:1014403393538:android:88dc9c31e9beacec5c9f1b',
    messagingSenderId: '1014403393538',
    projectId: 'pomodoro-knight-ed680',
    storageBucket: 'pomodoro-knight-ed680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoCSy5CJrTT9VBh8wMiwZfaUicZvaA17A',
    appId: '1:1014403393538:ios:a596ab26624aaed65c9f1b',
    messagingSenderId: '1014403393538',
    projectId: 'pomodoro-knight-ed680',
    storageBucket: 'pomodoro-knight-ed680.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroKnight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoCSy5CJrTT9VBh8wMiwZfaUicZvaA17A',
    appId: '1:1014403393538:ios:a596ab26624aaed65c9f1b',
    messagingSenderId: '1014403393538',
    projectId: 'pomodoro-knight-ed680',
    storageBucket: 'pomodoro-knight-ed680.firebasestorage.app',
    iosBundleId: 'com.example.pomodoroKnight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRdoEd3p-qAjCH1zegOn8V8C0ibdio1wo',
    appId: '1:1014403393538:web:4dfb041cc0bc8b6e5c9f1b',
    messagingSenderId: '1014403393538',
    projectId: 'pomodoro-knight-ed680',
    authDomain: 'pomodoro-knight-ed680.firebaseapp.com',
    storageBucket: 'pomodoro-knight-ed680.firebasestorage.app',
    measurementId: 'G-LF6VK5LD1Q',
  );
}
